Moving changes for remotable vivado to api-generator-sifive
sifive/api-generator-sifive pull request #1
Opened 2019-08-26 21:57 UTC by sistillson

Made changes into api-generator-sifive to enable vivado to run as a non-local job.

2019-08-27 20:00 UTC, richardxia requested changes

2019-08-27 20:00 UTC, richardxia commented on top.wake
> +    ++ sources firrtlRoot `.*\.sdc`
These two lines are duplicates of each other.

2019-08-27 20:00 UTC, richardxia commented on top.wake
> +    sources firrtlRoot `.*\.sdc`
You're not supposed to use `sources` for getting the paths to generated files. `sources` is meant to only describe "source" files, i.e. files that are committed to source control. I believe the next release of `wake` will enforce this. Instead, I believe the correct way of getting `Path` objects corresponding to generated files is to get them directly from the Job outputs.

2019-08-27 20:00 UTC, richardxia commented on top.wake
> +    ++ sources firrtlRoot `.*\.json`
Which JSON files are actually being used? The `.json` extension is not a great one to be filtering by, since there are a lot of files with very different semantic purposes that use that extension. I'm not sure I can remember off the top of my head any JSON files that actually should be used by the Bitstream building jobs.

2019-08-27 20:00 UTC, richardxia commented on fpga/mcs.wake
> +global def makeBitstreamPlan name vendor board topModule outputDir visibleFiles =
One comment I want make about this is that this is making a backwards incompatible change to a globally-defined function. Something we need to get better about as we split up the codebase is making sure that we do a better job of maintaining stable interfaces.

2019-08-27 20:44 UTC, sistillson commented on top.wake
> +    ++ sources firrtlRoot `.*\.sdc`
fixed

2019-08-27 20:44 UTC, sistillson commented on top.wake
> +    sources firrtlRoot `.*\.sdc`
fixed

2019-08-27 20:44 UTC, sistillson commented on top.wake
> +    ++ sources firrtlRoot `.*\.json`
will check

2019-08-27 20:45 UTC, sistillson commented on fpga/mcs.wake
> +global def makeBitstreamPlan name vendor board topModule outputDir visibleFiles =
agreed, but this is the best place to do it...

2019-08-28 00:23 UTC, richardxia commented on fpga/mcs.wake
> +global def makeBitstreamPlan name vendor board topModule outputDir visibleFiles =
Have we started tagging this repo with versions (such as sem-ver)? If so, we should at least increment part of the version number to indicate that a breaking change has been made.

2019-08-28 00:24 UTC, albertchen-sifive commented on fpga/mcs.wake
> +global def makeBitstreamPlan name vendor board topModule outputDir visibleFiles =
no we have not tagged this repo. and shouldn't this just use `Nil` as the default for `visibleFiles` instead of adding a new argument to this function?

2019-08-28 22:22 UTC, albertchen-sifive approved these changes

2019-08-28 22:23 UTC, merged